### ISSUE TITLE
Colour clash between background and foreground in help examples

### ISSUE THREAD

**Issue by ribecks98** [epmor/lampaces-demon-vim#2]
Currently, the background and foreground for examples in help windows are both set to colour 198 for 256 colour terminals (#ff0087 foreground and #ff0089 background), so it just looks pink. The issue is in these lines:

```
call <SID>X('helpExample',        s:base03, s:base01, '')
call <SID>X('helpSpecial',        s:base03, s:base01, '')
```

**Comment by epmor** [comment]
Thanks for reporting this. I've removed the `s:base01` similarly to how it is for all the others in help.
